##############################################################################################
#  Copyright Walmart Inc. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

- name: Ensure validator directory exist
  file:
    path: "{{ build_path }}/crypto/{{ org.name }}/{{ item.name  }}/data"
    state: directory
  with_items: "{{ org.services.peers is defined | ternary(org.services.peers, org.services.validators) }}"
# This tasks checks for the crypto material to the vault
- name: Check the crypto material in Vault
  shell: |
    vault kv get -field=key_pub {{ vault.secret_path | default('secretsv2') }}/{{ component_ns }}/crypto/{{ item.name }}/data > "{{ build_path }}/crypto/{{ org.name }}/{{ item.name  }}/data/key.pub"
    vault kv get -field=nodeAddress {{ vault.secret_path | default('secretsv2') }}/{{ component_ns }}/crypto/{{ item.name }}/data > "{{ build_path }}/crypto/{{ org.name }}/{{ item.name  }}/data/nodeAddress"
    vault kv get -field=key {{ vault.secret_path | default('secretsv2') }}/{{ component_ns }}/crypto/{{ item.name }}/data > "{{ build_path }}/crypto/{{ org.name }}/{{ item.name  }}/data/key"
  environment:
    VAULT_ADDR: "{{ vault.url }}"
    VAULT_TOKEN: "{{ vault.root_token }}"
  with_items: "{{ org.services.peers is defined | ternary(org.services.peers, org.services.validators) }}"
  register: vault_result
  ignore_errors: yes
