##############################################################################################
#  Copyright Accenture. All Rights Reserved.
#
#  SPDX-License-Identifier: Apache-2.0
##############################################################################################

# Build express app docker image triggered by :
#  - push on develop branch for latest tags
#  - create tag vx.y.z for release tags
#  - Can be triggered manually

name: Build Supplychain App Besu Images

on:
  workflow_dispatch:
  create:
    tags:
      - v*
  push:
    branches:
      - develop
    paths:
      - '.github/workflows/besu_expressapi.yaml'
      - 'examples/supplychain-app/besu/express_nodeJS/Dockerfile'

env:
  REGISTRY: ghcr.io
  IMAGE_PATH: ghcr.io/${{ github.repository_owner }}

jobs:
  # on push to develop branch, create docker tags latest
  besu-latest:
    if: ${{ startsWith(github.ref, 'refs/heads/develop') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Lowercase IMAGE_PATH
      id: image_path_format
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ env.IMAGE_PATH }}
    
    - name: Check node version
      run: node -v

    - name: Build and push supplychain app latest
      id: besu_supplychain_latest
      uses: docker/build-push-action@v2
      with:
        context: ./examples/supplychain-app/besu/express_nodeJS
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-supplychain-besu:express-app-latest

  besu-release: 
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set output
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/tags/v}
    
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    - name: Login to the container registry
      uses: docker/login-action@v1
      with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Lowercase IMAGE_PATH
      id: image_path_format
      uses: ASzc/change-string-case-action@v2
      with:
        string: ${{ env.IMAGE_PATH }}

    - name: Build and push supplychain app release
      id: besu_supplychain_release
      uses: docker/build-push-action@v2
      with:
        context: examples/supplychain-app/besu/express_nodeJS
        push: true
        tags: ${{ steps.image_path_format.outputs.lowercase }}/bevel-supplychain-besu:express-app-${{ steps.vars.outputs.tag }},${{ steps.image_path_format.outputs.lowercase }}/bevel-supplychain-quorum:express-app-stable
